apiVersion: v1
kind: Service
metadata:
    name: "kubernetangularui-3f93"
    labels:
        app: "kubernetangularui-3f93"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernetangularui-3f93"