on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: employeeregistrationserviceacr.azurecr.io
        username: ${{ secrets.acr_employeeregistrationserviceacr_username }}
        password: ${{ secrets.acr_employeeregistrationserviceacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t employeeregistrationserviceacr.azurecr.io/kubernetangularui:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push employeeregistrationserviceacr.azurecr.io/kubernetangularui:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernetangularui_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetangularui8cd9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetangularui8cd9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetangularui8cd9
        container-registry-url: employeeregistrationserviceacr.azurecr.io
        container-registry-username: ${{ secrets.acr_employeeregistrationserviceacr_username }}
        container-registry-password: ${{ secrets.acr_employeeregistrationserviceacr_password }}
        secret-name: kubernetangudockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernetangularui8cd9
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          employeeregistrationserviceacr.azurecr.io/kubernetangularui:${{ github.sha }}
        imagepullsecrets: |
          kubernetangudockerauth
